.TH __LIBJULIA_WIN_NT 1 2023-Nov "" "Solve the julia runtime on windows platform"
.SH NAME
__libjulia_win_nt \- __libjulia_win_nt()
.SH SYNOPSIS
\fI__libjulia_win_nt()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.__libjulia_win_nt at env.R:line 18
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
