.TH __LIBJULIA_ENV 1 2023-Nov "" "try to get the julia runtime for load library in clr runtime"
.SH NAME
__libjulia_env \- __libjulia_env()
.SH SYNOPSIS
\fI__libjulia_env()\fR
.SH VALUE
.PP
this function returns the library path to the julia runtime: 1. windows:  path to the ``libjulia.dll`` library file, 2. unix:  path to the ``libjulia.so`` library file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__libjulia_env at env.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
