.TH JL 1 2023-Nov "" "Execute the julia expression and evaluated as R# value"
.SH NAME
jl \- jl(script)
.SH SYNOPSIS
\fIjl(script)\fR
.SH OPTIONS
.PP
\fBscript\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.jl at jl.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
